query GetElection($id: ID!) {
  election(id: $id) {
    id
    name
    description
    status
    candidates {
      id
      name
      description
    }
    # results {
    #   winner {
    #     id
    #     name
    #     description
    #   }
    #   rounds {
    #     candidateTotals {
    #       candidate {
    #         name
    #       }
    #       votes
    #     }
    #     redistribution {
    #       candidate {
    #         name
    #       }
    #       votes
    #     }
    #   }
    # }
  }
}
